apps/institute_web/lib/institute_web/router.ex
defmodule InstituteWeb.Router do
  use InstituteWeb, :router

  alias Institute.Meetings

  pipeline :browser do
    plug(:accepts, ["html"])
    plug(:fetch_session)
    plug(:fetch_flash)
    plug(:protect_from_forgery)
    plug(:put_secure_browser_headers)
    plug(InstituteWeb.AuthPlug)
  end

  pipeline :api do
    plug(:accepts, ["json"])
  end

  scope "/auth", InstituteWeb do
    pipe_through(:browser)

    get("/:provider", AuthController, :request)
    # get("/:provider/callback", AuthController, :callback)
    post("/identity/callback", AuthController, :identity_callback)
    delete("/logout/:id", AuthController, :delete)
  end

  scope "/", InstituteWeb do
    pipe_through(:browser)

    get("/", PageController, :index)
    get("/code_of_conduct", PageController, :code_of_conduct)
    resources("/users", UserController, only: [:index, :show, :new, :create])
    get("#{Meetings.meeting_path()}", MeetingController, :index)
    get("#{Meetings.meeting_path()}/*path", MeetingController, :dynamic)
  end

  scope "/meeting", InstituteWeb do
    pipe_through(:browser)

    # get "/meeting/*path", MeetingController, :dynamic
    # get("/meeting/1", MeetingController, :page)
  end
  
  scope "/events", InstituteWeb do
    pipe_through([:browser, :authenticate_user])

    resources("/", EventController, only: [:index, :show, :new, :create, :edit, :update, :delete])
  end

  scope "/admin", InstituteWeb do
    pipe_through([:browser, :authenticate_user])

    get("/", PageController, :secret)
  end

  # Other scopes may use custom stacks.
  # scope "/api", InstituteWeb do
  #   pipe_through :api
  # end
end

apps/institute_web/lib/institute_web/controllers/auth_controller.ex
defmodule InstituteWeb.AuthController do
  @moduledoc """
  Auth controller responsible for handling Ueberauth responses
  """

  use InstituteWeb, :controller
  plug(Ueberauth)

  alias Ueberauth.Strategy.Helpers
  alias Institute.Accounts

  def request(conn, _params) do
    render(conn, "request.html", callback_url: Helpers.callback_url(conn))
  end

  def delete(conn, _params) do
    conn
    |> InstituteWeb.AuthPlug.logout()
    |> put_flash(:info, "You have been logged out!")
    |> redirect(to: "/")
  end

  def identity_callback(%{assigns: %{ueberauth_auth: auth}} = conn, _params) do
    username = auth.uid
    password = auth.credentials.other.password

    case Accounts.authenticate_by_username_and_pass(username, password) do
      {:ok, user} ->
        conn
        |> InstituteWeb.AuthPlug.login(user)
        |> put_flash(:info, "Successfully authenticated")
        |> redirect(to: "/")

      {:error, _reason} ->
        conn
        |> put_flash(:error, "Invalid username/password combination")
        |> redirect(to: "/")
    end
  end
end

apps/institute_web/lib/institute_web/controllers/event_controller.ex
defmodule InstituteWeb.EventController do
  use InstituteWeb, :controller

  alias Institute.Schedule
  alias Institute.Schedule.Event

  def index(conn, _params) do
    events = Schedule.list_events()
    render(conn, "index.html", events: events)
  end

  def new(conn, _params) do
    changeset = Schedule.change_event(%Event{})
    render(conn, "new.html", changeset: changeset)
  end

  def create(conn, %{"event" => event_params}) do
    case Schedule.create_event(event_params) do
      {:ok, event} ->
        conn
        |> put_flash(:info, "Event created successfully.")
        |> redirect(to: Routes.event_path(conn, :show, event))

      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "new.html", changeset: changeset)
    end
  end

  def show(conn, %{"id" => id}) do
    event = Schedule.get_event!(id)
    render(conn, "show.html", event: event)
  end

  def edit(conn, %{"id" => id}) do
    event = Schedule.get_event!(id)
    changeset = Schedule.change_event(event)
    render(conn, "edit.html", event: event, changeset: changeset)
  end

  def update(conn, %{"id" => id, "event" => event_params}) do
    event = Schedule.get_event!(id)

    case Schedule.update_event(event, event_params) do
      {:ok, event} ->
        conn
        |> put_flash(:info, "Event updated successfully.")
        |> redirect(to: Routes.event_path(conn, :show, event))

      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "edit.html", event: event, changeset: changeset)
    end
  end

  def delete(conn, %{"id" => id}) do
    event = Schedule.get_event!(id)
    {:ok, _event} = Schedule.delete_event(event)

    conn
    |> put_flash(:info, "Event deleted successfully.")
    |> redirect(to: Routes.event_path(conn, :index))
  end
end

apps/institute_web/lib/institute_web/controllers/meeting_controller.ex
defmodule InstituteWeb.MeetingController do
  use InstituteWeb, :controller

  alias Institute.Meetings

  # def page(conn, _params) do
  #   render(conn, "page.html")
  # end
  def dynamic(conn, _params) do
    render_dynamic(conn)
  end

  def index(conn, _params) do
    conn =
      conn
      |> assign(:meetings, Meetings.list_meetings())

    render(conn, "index.html")
  end
end

apps/institute_web/lib/institute_web/controllers/page_controller.ex
defmodule InstituteWeb.PageController do
  use InstituteWeb, :controller

  @code_of_conduct_html Path.join(:code.priv_dir(:institute_web), "code-of-conduct.md")
                        |> File.read!()
                        |> Earmark.as_html!()

  def index(conn, _params) do
    render(conn, "index.html")
  end

  def code_of_conduct(conn, _params) do
    html(conn, @code_of_conduct_html)
  end

  def secret(conn, _params), do: html(conn, "This is secret.")
end

apps/institute_web/lib/institute_web/controllers/user_controller.ex
defmodule InstituteWeb.UserController do
  use InstituteWeb, :controller

  alias Institute.Accounts
  alias Institute.Accounts.User

  plug :authenticate_user when action in [:index, :show]

  def index(conn, _params) do
    users = Accounts.list_users()
    render(conn, "index.html", users: users)
  end

  def show(conn, %{"id" => id}) do
    user = Accounts.get_user(id)
    render(conn, "show.html", user: user)
  end

  def new(conn, _params) do
    changeset = Accounts.change_registration(%User{}, %{})
    render(conn, "new.html", changeset: changeset)
  end

  def create(conn, %{"user" => user_params}) do
    case Accounts.register_user(user_params) do
      {:ok, user} ->
        conn
        |> put_flash(:info, "#{user.name} created!")
        |> redirect(to: Routes.user_path(conn, :index))

      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "new.html", changeset: changeset)
    end
  end
end

apps/institute_web/lib/institute_web/views/auth_view.ex
defmodule InstituteWeb.AuthView do
  @moduledoc false

  use InstituteWeb, :view
end

apps/institute_web/lib/institute_web/views/error_view.ex
defmodule InstituteWeb.ErrorView do
  use InstituteWeb, :view

  # If you want to customize a particular status code
  # for a certain format, you may uncomment below.
  # def render("500.html", _assigns) do
  #   "Internal Server Error"
  # end

  # By default, Phoenix returns the status message from
  # the template name. For example, "404.html" becomes
  # "Not Found".
  def template_not_found(template, _assigns) do
    Phoenix.Controller.status_message_from_template(template)
  end
end

apps/institute_web/lib/institute_web/views/event_view.ex
defmodule InstituteWeb.EventView do
  use InstituteWeb, :view
end

apps/institute_web/lib/institute_web/views/layout_view.ex
defmodule InstituteWeb.LayoutView do
  use InstituteWeb, :view

  alias InstituteWeb.MeetingController
  alias InstituteWeb.PageController

  def show_thesis_editor?(conn) do
    action = conn.private.phoenix_action
    controller = conn.private.phoenix_controller
    show_menu_on_page?({controller, action})
  end

  defp show_menu_on_page?({PageController, :index}), do: true
  defp show_menu_on_page?({MeetingController, _action}), do: true
  defp show_menu_on_page?({_, _}), do: false
end

apps/institute_web/lib/institute_web/views/meeting_view.ex
defmodule InstituteWeb.MeetingView do
  use InstituteWeb, :view
end

apps/institute_web/lib/institute_web/views/page_view.ex
defmodule InstituteWeb.PageView do
  use InstituteWeb, :view

  alias Institute.Meetings

  def next_meeting do
    Meetings.next_meeting()
  end

  def fmt_mtg_content(%{content: content, type: "html"}) do
    raw(content)
  end

  def fmt_mtg_content(%{content: content, type: _type}) do
    content
  end

  @doc """
  Guards agains a nil stored in the DB.

  Returns blank as a last resort.
  """
  def fmt_mtg_content(_), do: ""
end

apps/institute_web/lib/institute_web/views/user_view.ex
defmodule InstituteWeb.UserView do
  use InstituteWeb, :view

  alias Institute.Accounts

  def first_name(%Accounts.User{name: name}) do
    name
    |> String.split(" ")
    |> Enum.at(0)
  end
end

apps/institute_web/lib/institute_web/templates/event/edit.html.eex
<h1>Edit Event</h1>

<%= render "form.html", Map.put(assigns, :action, Routes.event_path(@conn, :update, @event)) %>

<span><%= link "Back", to: Routes.event_path(@conn, :index) %></span>

apps/institute_web/lib/institute_web/templates/event/form.html.eex
<%= form_for @changeset, @action, [class: "event-form"], fn f -> %>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below.</p>
    </div>
  <% end %>

  <div class="container">
    <div class="row form-row">
      <div class="col">
        <%= label f, :title %>
        <%= text_input f, :title, class: "form-control" %>
        <%= error_tag f, :title %>
      </div>
    </div>
    
    <div class="row form-row">
      <div class="col">
        <%= label f, :description %>
        <%= textarea f, :description, class: "form-control" %>
        <%= error_tag f, :description %>
      </div>
    </div>
    
    <div class="row form-row">
      <div class="col">
        <%= label f, :sub_heading %>
        <%= text_input f, :sub_heading, class: "form-control" %>
        <%= error_tag f, :sub_heading %>
      </div>
    </div>
    
    <div class="row form-row">
      <div class="col">
        <%= label f, :event_start_datetime %>
        <%= datetime_select f, :event_start_datetime, class: "form-control" %>
        <%= error_tag f, :event_start_datetime %>
      </div>
    </div>
    
    <div class="row form-row">
      <div class="col">
        <%= label f, :event_timezone %>
        <%= text_input f, :event_timezone, class: "form-control" %>
        <%= error_tag f, :event_timezone %>
      </div>
    </div>

    <div class="row form-row">
      <div class="col">
        <%= label f, :event_end_datetime %>
        <%= datetime_select f, :event_end_datetime, class: "form-control" %>
        <%= error_tag f, :event_end_datetime %>
      </div>
    </div>

    <div class="row form-row">
      <div class="col">
        <%= label f, :location %>
        <%= text_input f, :location, class: "form-control" %>
        <%= error_tag f, :location %>
      </div>
    </div>

    <div class="row form-row">
      <div class="col">
        <%= label f, :address %>
        <%= text_input f, :address, class: "form-control" %>
        <%= error_tag f, :address %>
      </div>
    </div>

    <div class="row form-row">
      <div class="col">
        <%= label f, :video_url %>
        <%= text_input f, :video_url, class: "form-control" %>
        <%= error_tag f, :video_url %>
      </div>
    </div>

    <div class="row form-row">
      <div class="col">
        <%= submit "Save" %>
      </div>
    </div>
  </div>
<% end %>

apps/institute_web/lib/institute_web/templates/event/index.html.eex
<h1>Listing Events</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Sub heading</th>
      <th>Event start datetime</th>
      <th>Event timezone</th>
      <th>Event end datetime</th>
      <th>Location</th>
      <th>Address</th>
      <th>Video url</th>

      <th></th>
    </tr>
  </thead>
  <tbody>
<%= for event <- @events do %>
    <tr>
      <td><%= event.title %></td>
      <td><%= event.description %></td>
      <td><%= event.sub_heading %></td>
      <td><%= event.event_start_datetime %></td>
      <td><%= event.event_timezone %></td>
      <td><%= event.event_end_datetime %></td>
      <td><%= event.location %></td>
      <td><%= event.address %></td>
      <td><%= event.video_url %></td>

      <td>
        <%= link "Show", to: Routes.event_path(@conn, :show, event) %>
        <%= link "Edit", to: Routes.event_path(@conn, :edit, event) %>
        <%= link "Delete", to: Routes.event_path(@conn, :delete, event), method: :delete, data: [confirm: "Are you sure?"] %>
      </td>
    </tr>
<% end %>
  </tbody>
</table>

<span><%= link "New Event", to: Routes.event_path(@conn, :new) %></span>

apps/institute_web/lib/institute_web/templates/event/new.html.eex
<h1>New Event</h1>

<%= render "form.html", Map.put(assigns, :action, Routes.event_path(@conn, :create)) %>

<span><%= link "Back", to: Routes.event_path(@conn, :index) %></span>

apps/institute_web/lib/institute_web/templates/event/show.html.eex
<h1>Show Event</h1>

<ul>

  <li>
    <strong>Title:</strong>
    <%= @event.title %>
  </li>

  <li>
    <strong>Description:</strong>
    <%= @event.description %>
  </li>

  <li>
    <strong>Sub heading:</strong>
    <%= @event.sub_heading %>
  </li>

  <li>
    <strong>Event start datetime:</strong>
    <%= @event.event_start_datetime %>
  </li>

  <li>
    <strong>Event timezone:</strong>
    <%= @event.event_timezone %>
  </li>

  <li>
    <strong>Event end datetime:</strong>
    <%= @event.event_end_datetime %>
  </li>

  <li>
    <strong>Location:</strong>
    <%= @event.location %>
  </li>

  <li>
    <strong>Address:</strong>
    <%= @event.address %>
  </li>

  <li>
    <strong>Video url:</strong>
    <%= @event.video_url %>
  </li>

</ul>

<span><%= link "Edit", to: Routes.event_path(@conn, :edit, @event) %></span>
<span><%= link "Back", to: Routes.event_path(@conn, :index) %></span>

apps/institute_web/lib/institute_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Hawaiʻi Umbrella Institute for the Advancement of Developers</title>
    <link rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app.css") %>"/>
  </head>
  <body class="app-layout">
    <%= if show_thesis_editor?(@conn) do %>
      <%= thesis_editor(@conn) %>
    <% end %>
    <%= render("header.html", conn: @conn, current_user: @current_user, view: [@view_module, @view_template]) %>
    <main role="main" class="container">
      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
      <%= @inner_content %>
    </main>
    <script type="text/javascript" src="<%= Routes.static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>

apps/institute_web/lib/institute_web/templates/layout/header.html.eex
<header>
  <section class="container-fluid">
    <nav role="navigation">
      <ul>
        <%= if @current_user do %>
          <li>Hello, <%= @current_user.username %>! </li>
          <li><%= link "Log out", to: Routes.auth_path(@conn, :delete, @current_user), method: "delete" %></li>
        <% else %>
          <li><%= link "Log in", to: Routes.auth_path(@conn, :request, :identity) %></li>
        <% end %>
      </ul>
    </nav>
    <%= if @view == [InstituteWeb.PageView, "index.html"] do %>
      <%= render("home_link.html", conn: @conn) %>
    <% else %>
      <a href="<%= Routes.page_path(@conn, :index) %>" alt="Home" class="home-link">
        <%= render("home_link.html", conn: @conn) %>
      </a>
    <% end %>
  </section>
</header>

apps/institute_web/lib/institute_web/templates/layout/home_link.html.eex
<div class="d-flex align-items-end group-title-container">
  <div class="group-title">
    <span>
      <%= global_content(@conn, "Group Title", :text) do %>
        Welcome to the Institute
      <% end %>
    </span>
    <small>
      <%= global_content(@conn, "Group Sub-Heading", :text) do %>
        The Hawaiʻi Umbrella Institute for the Advancement of Developers
      <% end %>
    </small>
  </div>
</div>

apps/institute_web/lib/institute_web/templates/meeting/index.html.eex
<div class="meeting-list">
  <ul class="list-unstyled">
    <%=  for m <- @meetings do %>
      <li><a href="<%= m.slug %>" alt="meeting"><%= m.title %></a> - <small><%= m.description %></small></li>
    <% end %>
  </ul>
</div>

apps/institute_web/lib/institute_web/templates/meeting/page.html.eex
<div class="meeting">
  <article>
    <h1 class="helvetica">
      <small>
        <%= content(@conn, "Meeting Type", :text) do %>
          Meeting
        <% end %>
      </small>
      <%= content(@conn, "Meeting Title", :text) do %>
        <%= @thesis_page.title %>
      <% end %>
    </h1>
    <h2 class="helvetica">
      <%= content(@conn, "Meeting Sub-heading", :text) do %>
        A birds guide to functional programming
      <% end %>
    </h2>
  </article>
  <section>
    <div class="row">
      <div class="col-md-12">
        <ul>
          <li><%= content(@conn, "Time", :text, do: "Time: 7-8pm") %></li>
          <li><%= content(@conn, "Day", :text, do: "Day: Wednesday, Jan. 1, 2019") %></li>
          <li>
            <%= content(@conn, "Location", :html) do %>
              <a href="https://sandboxhawaii.org/" alt="Sandbox website">HTDC Sandbox</a>
            <% end %>
          </li>
          <li>
            <%= content(@conn, "Address", :html) do %>
              <a href="https://www.google.com/maps/place/643+Ilalo+St,+Honolulu,+HI+96813/@21.296994,-157.8657639,17z/data=!3m1!4b1!4m5!3m4!1s0x7c006e0f5b137809:0x5be3e1f3c9fc3d8d!8m2!3d21.296994!4d-157.8635752" alt="Sandbox map">643 Ilalo St. Honolulu, HI 96813</a>
            <% end %>
          </li>
        </ul>
        <%= content(@conn, "Event Description", :html) do %>
          <p><%= @thesis_page.description %></p>
        <% end %>
      </div>
    </div>
  </section>
  <section>
    <h1 class="helvetica">
      <%= content(@conn, "Description Sub-Heading", :text, do: "Description Sub-heading") %>
    </h1>
    <div class="row">
      <div class="col-md-12">
        <%= content(@conn, "Additional Description", :html) do %>
          <p>Selfies hashtag meh biodiesel keytar chillwave lomo iceland PBR&B gastropub bespoke iPhone pour-over hot chicken. Coloring book hashtag leggings 90's typewriter, tattooed flannel celiac godard freegan sartorial prism. Pork belly activated charcoal gastropub vegan air plant church-key butcher migas lyft tofu. Small batch shoreditch ugh hell of butcher put a bird on it, master cleanse deep v fashion axe iPhone edison bulb. Vape unicorn flexitarian schlitz. Art party schlitz edison bulb cliche vinyl austin fingerstache iPhone forage truffaut.</p>
          <p>Biodiesel synth selvage fixie PBR&B la croix shaman pickled copper mug sustainable vinyl readymade. Echo park sriracha vaporware single-origin coffee you probably haven't heard of them crucifix raclette four loko taiyaki tumblr health goth flexitarian chambray. Heirloom taiyaki letterpress occupy. Try-hard put a bird on it stumptown disrupt squid YOLO sriracha 3 wolf moon fanny pack cliche adaptogen sustainable pitchfork fixie snackwave.</p>
        <% end %>
      </div>
        </div>
  </section>
</div>

apps/institute_web/lib/institute_web/templates/page/index.html.eex
<div class="front-page">
  <section>
    <div class="row">
      <div class="col-md-6 description">
        <%= content(@conn, "Group Description", :html) do %>
          <h1>👋 Hello Fellow Programmers</h1>
          <p>Hey programming fans, some local programmers have been mulling over some ideas for a reboot of Elixir meetups. But, really we want to meet and share our interest in programming in general. This website is one of the results of those discussions. It's a place to list upcoming meetings and workshops, record previous events, and showcase fun side-projects. There's not a lot here yet, but reach out if you have suggestions.</p>
          <p>We are a community of programmers which hangs out on Slack and IRL around programming events, such as talks and workshops. The goal of these events is usually some form of collaborative learning. The programming community is small in general, but close-knit. These events give us a way to meet each other, stay in touch, and share our experiences.</p>
          <p>We recognize that close-knit communities can seem cliquish, and more established members can appear snobbish or arrogant protectors of their domains. We hope to actively fight against these perceptions and create a friendly space for collaboration.</p>
          <h2>What we strive to do</h2>
          <ul>
            <li>[Borrowed from the <a href="https://p5js.org/community/" alt="P5JS community page">P5JS community</a>]</li>
            <li>We are not code snobs. We do not assume knowledge or imply there are things that somebody should know.</li>
            <li>We insist on actively engaging with requests for feedback regardless of their complexity.</li>
            <li>We welcome newcomers and prioritize the education of others. We strive to approach all tasks with the enthusiasm of a newcomer. Because we believe that newcomers are just as valuable in this effort as experts.</li>
            <li>We consistently make the effort to actively recognize and validate multiple types of contributions.</li>
            <li>We are always willing to offer help or guidance.</li>
          </ul>
          <h2>When problems arise</h2>
          <ul>
            <li>[Also borrowed from the <a href="https://p5js.org/community/" alt="P5JS community page">P5JS community</a>]</li>
            <li>We listen.</li>
            <li>We clearly communicate while acknowledging other's feelings.</li>
            <li>We admit when we're wrong, apologize, and accept responsibility for our actions.</li>
            <li>We are continuously seeking to improve ourselves and our community.</li>
            <li>We keep our community respectful and open.</li>
            <li>We make everyone feel heard.</li>
            <li>We are mindful and kind in our interactions.</li>
          </ul>
        <% end %>
      </div>
      <div class="col-md-4 next-meeting">
        <h2 class="next-heading">Next Meeting:</h2>
        <%= render("next_meeting.html", meeting: next_meeting(), conn: @conn) %>
      </div>
      <div class="col-md-2">
        <ul class="list-unstyled resource-links">
          <li>
            <%= link "Code of Conduct", to: Routes.page_path(@conn, :code_of_conduct) %>
          </li>
          <li>
            <%= link "Meetings Archive", to: Routes.meeting_path(@conn, :index) %>
          </li>
          <%= if @current_user do %>
          <li>
            <%= link "Create user", to: Routes.user_path(@conn, :new) %>
          </li>
          <% end %>
        </ul>
      </div>
    </div>
  </section>
</div>

apps/institute_web/lib/institute_web/templates/page/next_meeting.html.eex
<%= case @meeting do %>
  <% %{page: page, content: content} -> %>
  <a href="<%= page.slug %>" alt="Meeting details">
    <h3>
      <%= fmt_mtg_content(content.event_title) %>
      <small>&#8212;<%= fmt_mtg_content(content.event_sub_heading) %></small>
    </h3>
  </a>
  <ul>
    <li><%= fmt_mtg_content(content.event_time) %></li>
    <li><%= fmt_mtg_content(content.event_day) %></li>
    <li>
      <%= fmt_mtg_content(content.event_location) %>
    </li>
    <li>👉 <a href="<%= page.slug %>" alt="Meeting details">See event details</a></li>
  </ul>
  <p>
    <%= fmt_mtg_content(content.event_description) %>
    <small>
      👉 <a href="<%= page.slug %>" alt="Meeting details">More details</a>
    </small>
  </p>
  <p></p>
  <% nil -> %>
  <p>No meeting planned yet.</p>
<% end %>

apps/institute_web/lib/institute_web/templates/user/index.html.eex
<h1>Listing Users</h1>

<table>
  <%= for user <- @users do %>
    <tr>
      <td><b><%= first_name(user) %></b> (<%= user.id %>)</td>
      <td><%= link "View", to: Routes.user_path(@conn, :show, user.id) %></td>
    </tr>
  <% end %>
</table>

apps/institute_web/lib/institute_web/templates/user/new.html.eex
<h1>New User</h1>

<%= form_for @changeset, Routes.user_path(@conn, :create), fn f -> %>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below.</p>
    </div>
  <% end %>

  <div>
    <%= text_input f, :name, placeholder: "Name" %>
    <%= error_tag f, :name %>
  </div>
  <div>
    <%= text_input f, :username, placeholder: "Username" %>
    <%= error_tag f, :username %>
  </div>
  <div>
    <%= password_input f, :password, placeholder: "Password" %>
    <%= error_tag f, :password %>
  </div>
  <%= submit "Create User" %>
<% end %>

apps/institute_web/lib/institute_web/templates/user/show.html.eex
<h1>Showing User</h1>
<b><%= first_name(@user) %></b> (<%= @user.id %>)